pato1 program tabla_de_2;
var i, acumulador : ;
void funci (a : int) [
  var i, acumulador : int;
  {
    acumulador = 0;
  }
];
void funci2 (a : int,) [
  var i, acumulador : int;
  {
    acumulador = 0;
  }
];
pato2
main {
  i = 1;
  acumulador = 0;
  pato3
  print(a b);
  do {
    acumulador = acumulador + 2;
    pato4
    print( acumulador );
  } while (i < 11);
  print("Final");
  pato = pato4 pato5
}
# un patoprograma de ejemplo
# quack!